development:
  adapter: postgresql
  encoding: unicode
  database: launcher_journal_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: launcher_journal_test
  pool: 5
  username:
  password:

